repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/douira/commitlint-pre-commit
    rev: v12.1.1
    hooks:
      - id: commitlint
        name: Conventional Commits
        # You can pin or override commitlint configs here:
        additional_dependencies:
          - "@commitlint/config-conventional@12.1.1"
