repos:
  - repo: local
    hooks:
      - id: commit-message-format
        name: Commit Message Format
        entry: hooks/commit-msg
        language: script
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
