#!/bin/sh
# This script checks the format of commit messages.

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Regex to match the required format: [TYPE]: Message
REGEX="^\[(INIT|REF|CONFIG|FIX|WIP)\]: .+"

if [[ ! $COMMIT_MSG =~ $REGEX ]]; then
    echo "Error: Commit message must follow the format '[TYPE]: Message'"
    echo "Valid types: INIT, REF, CONFIG, FIX, WIP"
    exit 1
fi

# Check if the commit message is empty
if [ ! -s "$COMMIT_MSG" ]; then
    echo "Error: Commit message is empty." >&2
    exit 1
fi

exit 0
